---
version: '3.8'
services:
  frontend:
    build:
      context: ./IMAKube-ui
      dockerfile: Dockerfile
    environment:
      - VITE_PORT=8080
      - VITE_ORIGIN=http://localhost:8080
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge